syntax = "proto3";

package scanner;

option go_package = "ghostwyre/scanner/pb";

enum ScanType {
    UNKNOWN = 0;
    QUICK = 1;
    FULL = 2;
}

message ScanRequest {
    string target = 1;
    ScanType scan_type = 2;
}

message SiteInfo {
    int32 status = 1;
    string content_type = 2;
    string origin = 3;
    string date_of_scanning = 4;
    string server = 5;
    string connection_status = 6;
    string csp = 7;
}

message ScanResponse {
    SiteInfo site_info = 1;
}


service ScannerService {
    rpc StartScan(ScanRequest) returns (ScanResponse);
}